### ISSUE TITLE
关于如何参与到翻译中

### ISSUE THREAD

**Issue by AlphaStarguide** [fvtt-cn/pf2_cn#1]
你好
我最近想加一些自己游戏中会用到的部分的汉化到PF2E的汉化MOD中。
我查看了说明部分并访问了weblate，但是添付的链接好像失效了。
我去weblate官网在所有Project里尝试用关键词搜索页也没有找到本汉化。
想请问现在想要参与翻译的话有什么方法吗？
谢谢。

**Comment by hmqgg** [comment]
Weblate 恢复时间大概是 23/25 号以后。

**Comment by AlphaStarguide** [comment]
啊所以Weblate是暂时性不能用而已是吗。
了解了。谢谢。

**Comment by hmqgg** [comment]
@AlphaStarguide 已恢复运作。

**Comment by AlphaStarguide** [comment]
@hmqgg 
谢谢！想再请问一下如果想要翻译现在weblate上以外的内容要怎么添加进去呢？

**Comment by hmqgg** [comment]
参见 [mega_chn](https://github.com/fvtt-cn/mega_chn)

**Comment by AlphaStarguide** [comment]
@hmqgg 
哦不好意思我没表达清楚。
不是别的MOD或者系统，是PF2E系统整合包里一些没有在PF2ECN的weblate里的内容（比如族裔和职业这些）

**Comment by AlphaStarguide** [comment]
@hmqgg 不好意思，可以麻烦问一下如何翻译族裔或职业这些整合包内容吗

**Comment by hmqgg** [comment]
> @hmqgg 不好意思，可以麻烦问一下如何翻译族裔或职业这些整合包内容吗

修改 `.db` 文件。

**Comment by AlphaStarguide** [comment]
@hmqgg 我尝试修改了本地的.db里的.jason文件，成功达成了汉化的效果。但是这样的话只要pf2e系统一更新我的修改就会被覆盖吧？我要如何将修改好的已翻译.jason上传到这个项目呢？
