### ISSUE TITLE
启用PF2系统中文会导致角色最大HP计算错误

### ISSUE THREAD

**Issue by AlphaStarguide** [fvtt-cn/pf2_cn#4]
禁用全部模组时，最大HP正常计算
![image](https://user-images.githubusercontent.com/90250769/149610954-f966b50a-9d8b-4f90-8cc2-0164b3091ee9.png)
![image](https://user-images.githubusercontent.com/90250769/149610985-e148ece9-d074-476e-a223-cdff9c70f349.png)

魔战士8+体质调整值1+精灵6=15最大生命值

打开PF2翻译后
![image](https://user-images.githubusercontent.com/90250769/149611016-3225c13f-84c9-4923-90b5-ab52b2db0a3a.png)
![image](https://user-images.githubusercontent.com/90250769/149611021-615c58a5-bac0-4b94-be21-bd0a09e72f24.png)
![image](https://user-images.githubusercontent.com/90250769/149611011-9f30d02a-1888-4345-831f-9a996fa97634.png)
自动计算没有加上职业的生命值

**Comment by AlphaStarguide** [comment]
顺便试了一下，把cn.json中的
```
        "ClassHP": "职业 HP",
```
一行删去可以临时解决这个BUG

**Comment by hmqgg** [comment]
那也就是不翻译此段内容。尽量是修复 pf2 系统以解决此问题。
